name: Generate Profile Widgets

on:
  schedule:
    # 每天 UTC 时间 18:00 (北京时间凌晨 2:00) 自动运行一次
    - cron: "25 17 * * *"
  workflow_dispatch: # 允许手动触发运行
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D contrib graph
        uses: yoshi389111/github-profile-3d-contrib@0.8.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
          USERNAME: ${{ github.repository_owner }}

      - name: Collect all outputs
        run: cp profile-3d-contrib/* dist/

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
